apiVersion: v1
kind: Service
metadata:
  name: service-cluster-ip
spec:
  selector:
    app: technews-services
  ports:
    - name: rabbit-mq
      protocol: TCP
      port: 15672
      targetPort: 15672
    
    - name: event-store
      protocol: TCP
      port: 2113
      targetPort: 2113